spring.application.name=lovelink

# Server port (Render requirement)
server.port=${PORT:8080}
# PostgreSQL datasource (Render)
spring.datasource.url=${postgresql://lovelink_user:SRhhriQv3FlWl9KjD0Od6Ndm01OEAnTS@dpg-d63fn8kr85hc73b6e9t0-a/lovelink}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




